### ISSUE TITLE
not working when built

### ISSUE THREAD

**Issue by nicoloserafino** [keijiro/KlakSyphon#9] opened 2018-10-09 12:49 UTC
Is it normal that my app is not working when built?
Can't see the stream on mad mapper

**Comment by keijiro** [comment] 2018-10-10 00:47
Thanks for reporting. Could you send the Player log? I'd like to looking into it.

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by keijiro** [comment] 2018-10-10 04:47
Also you can try the latest update, not sure if it's relevant though.

https://github.com/keijiro/KlakSyphon/releases/tag/v0.0.3

**Comment by nicoloserafino** [comment] 2018-10-10 15:03
Hi keijiro, thank you.
Checking the Player log, I managed to make it work simply changing the architecture target of my Build Settings from x86_64 to Universal.

Anyway the player log is attached for study purposes
"Connection socket refused" because my app needs a required device that is not connected.
[Player.log](https://github.com/keijiro/KlakSyphon/files/2465228/Player.log)

**Comment by keijiro** [comment] 2018-10-10 15:55
Thanks for the additional information. Although the root cause is still not clear, I'm happy to hear that the problem was solved on your side.

I'm closing this issue. I'll revisit it when it reproduces in some way.

**Closed as completed by keijiro** 2018-10-10 15:55 UTC
Labels: question
